stages:
- buildah
- envsubst
- kubectl


buildah:
  image: twobrowin/gitlab-runners:buildah
  stage: buildah
  script:
  - buildah --storage-driver=vfs bud -t $DOCKER_PUSH_REGISTRY/front:${CI_COMMIT_BRANCH}-${CI_COMMIT_SHORT_SHA} .
  - buildah push --storage-driver=vfs --tls-verify=false --creds $DOCKER_PUSH_CREDS $DOCKER_PUSH_REGISTRY/front:${CI_COMMIT_BRANCH}-${CI_COMMIT_SHORT_SHA}

envsubst:
  image: twobrowin/gitlab-runners:envsubs
  stage: envsubst
  script:
  - envsubst -i front.yaml -o front-${CI_COMMIT_BRANCH}-${CI_COMMIT_SHORT_SHA}.yaml
  artifacts:
    paths:
    - front-${CI_COMMIT_BRANCH}-${CI_COMMIT_SHORT_SHA}.yaml
    expire_in: 30 minutes

kubectl:
  image: twobrowin/gitlab-runners:kubectl
  stage: kubectl
  script:
  - kubectl --kubeconfig $KUBECTL_CONFIG --token $KUBECTL_USER_TOCKEN apply --record -f front-${CI_COMMIT_BRANCH}-${CI_COMMIT_SHORT_SHA}.yaml